apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonAnnotations:
  app.kubernetes.io/version: v0.30.0
  catalog.kubestack.com/heritage: kubestack.com/catalog/nginx
  catalog.kubestack.com/variant: base
commonLabels:
  app.kubernetes.io/component: ingress-controller
  app.kubernetes.io/managed-by: kubestack
  app.kubernetes.io/name: nginx
patchesStrategicMerge:
- patch-replicas.yaml
resources:
- mandatory.yaml
images:
- name: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
  newTag: 0.30.0
